name: PR Description Lint

on:
  pull_request_target:
    types: [opened, edited, synchronize]
    branches: [dev, master]

permissions:
  issues: write
  pull-requests: write

jobs:
  check-description:
    runs-on: ubuntu-latest
    steps:
      - name: Validate PR description
        uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request;
            const maxAttempts = 5;
            const label = 'invalid-description';
            const attemptLabelPrefix = 'description-attempt-';
            const description = pr.body ? pr.body.trim() : '';

            function getAttemptCount(labels) {
              const attemptLabel = labels.find(l => l.name.startsWith(attemptLabelPrefix));
              return attemptLabel ? parseInt(attemptLabel.name.replace(attemptLabelPrefix, '')) : 0;
            }

            if (!description || description.length < 20) {
              await github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: pr.number,
                labels: [label]
              });

              const labels = pr.labels;
              let attempts = getAttemptCount(labels) + 1;
              for (const l of labels) {
                if (l.name.startsWith(attemptLabelPrefix)) {
                  await github.rest.issues.removeLabel({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    issue_number: pr.number,
                    name: l.name
                  });
                }
              }
              await github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: pr.number,
                labels: [`${attemptLabelPrefix}${attempts}`]
              });

              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: pr.number,
                body: `👋 Hi @${pr.user.login}, your PR description doesn't meet our guidelines. Please update it to provide enough context (at least 20 characters).\n\nYou have ${maxAttempts - attempts} attempts left. If not fixed within 30 minutes or after 5 failed attempts, this PR will be closed.`
              });

              core.setFailed('PR description is not valid.');
            } else {
              for (const l of pr.labels) {
                if (l.name === label || l.name.startsWith(attemptLabelPrefix)) {
                  await github.rest.issues.removeLabel({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    issue_number: pr.number,
                    name: l.name
                  });
                }
              }
            } 