name: PR Title Lint

on:
  pull_request:
    types: [opened, edited, synchronize]
    branches: [dev, master]

jobs:
  check-title:
    runs-on: ubuntu-latest
    steps:
      - name: Validate PR title
        uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request;
            const badTitles = ['update', 'fix', 'wip', 'test', 'changes'];
            const title = pr.title.trim().toLowerCase();
            const maxAttempts = 5;
            const label = 'invalid-title';
            const attemptLabelPrefix = 'title-attempt-';

            // Helper to get attempt count from labels
            function getAttemptCount(labels) {
              const attemptLabel = labels.find(l => l.name.startsWith(attemptLabelPrefix));
              return attemptLabel ? parseInt(attemptLabel.name.replace(attemptLabelPrefix, '')) : 0;
            }

            // Check title
            if (badTitles.includes(title) || title.length < 10) {
              // Add invalid label
              await github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: pr.number,
                labels: [label]
              });

              // Increment attempt count
              const labels = pr.labels;
              let attempts = getAttemptCount(labels) + 1;
              // Remove old attempt labels
              for (const l of labels) {
                if (l.name.startsWith(attemptLabelPrefix)) {
                  await github.rest.issues.removeLabel({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    issue_number: pr.number,
                    name: l.name
                  });
                }
              }
              await github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: pr.number,
                labels: [`${attemptLabelPrefix}${attempts}`]
              });

              // Comment to user
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: pr.number,
                body: `👋 Hi @${pr.user.login}, your PR title doesn't meet our guidelines. Please update it to be descriptive (at least 10 characters, not generic like "update", "fix", etc.).\n\nYou have ${maxAttempts - attempts} attempts left. If not fixed within 30 minutes or after 5 failed attempts, this PR will be closed.`
              });

              // Fail the check
              core.setFailed('PR title is not valid.');
            } else {
              // Remove invalid label and attempt labels if fixed
              for (const l of pr.labels) {
                if (l.name === label || l.name.startsWith(attemptLabelPrefix)) {
                  await github.rest.issues.removeLabel({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    issue_number: pr.number,
                    name: l.name
                  });
                }
              }
            } 